GET http://localhost:3001/todos/?search_q=Submit
###

GET http://localhost:3001/todos/24/
###


GET http://localhost:3001/agenda/?date=2021-1-12
###


POST http://localhost:3001/todos/
Content-Type: application/json

{
 "id": 24,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}

###

PUT http://localhost:3001/todos/5/
Content-Type: application/json

{ "status": "DONkE" }
###


DELETE  http://localhost:3001/todos/20/